# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us,ru
    follow_mouse = 1
    numlock_by_default = true
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
        scroll_factor = 0.3
    }
}

gestures {
    workspace_swipe_distance = 1000
    workspace_swipe_min_speed_to_force = 10
}

gesture = 4, horizontal, workspace
gesture = 4, vertical, dispatcher, hyprexpo:expo, toggle
gesture = 3, swipe, move
gesture = 3, swipe, mod: ALT, resize