# https://wiki.hypr.land/Configuring/Window-Rules/
# https://wiki.hypr.land/Configuring/Workspace-Rules/

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = ignore-maximize
  suppress_event = maximize
  match:class = .*
}


# Fix some dragging issues with XWayland
windowrule {
  name = xwayland-drag-fix
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}


# Vicinae
layerrule {
  name = vicinae-blur
  blur = on
  ignore_alpha = 0
  match:namespace = vicinae
}

windowrule {
  name = vicinae-borderless
  border_size = 0
  match:class = vicinae
}


# Swaync
layerrule {
  name = swaync-control-center-blur
  blur = on
  ignore_alpha = 0.5
  animation = slide right
  match:namespace = swaync-control-center
}

layerrule {
  name = swaync-notification-window-blur
  blur = on
  ignore_alpha = 0.5
  match:namespace = swaync-notification-window
}





# Swayosd
layerrule {
  name = swayosd-blur
  blur = on
  ignore_alpha = 0.3
  match:namespace = swayosd
}


# Media viewers should be opaque to not mess with the content
windowrule {
  name = media-viewers-opaque
  opaque = on
  float = on
  match:class = org.gnome.Loupe
  match:class = (.*)(Celluloid)
}


# Waybar
layerrule {
  name = waybar-blur
  blur = on
  ignore_alpha = 0.3
  match:namespace = waybar
}
